=== PackOfDingoes/TopDown2dCharacterController/Assets/Assets/xml things DON'T DELETE/ItemDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="ItemDatabase" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="ItemDatabase">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="iqIOsSWeO0qvNgaAxtoMrQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACKog6xJZ47Sq82BoDG2gytAAAAAFGzVc72wORAAAAAAAAAAABJAHQA
ZQBtAEQAYQB0AGEAYgBhAHMAZQAAAAAAAADPmoN0d+UfTozEI5d2JSKKBwAAAIqi
DrElnjtKrzYGgMbaDK1OAGEAbQBlAAAAAAAAAJOgqz4GLv1PmSkX+1lRDoYHAAAA
iqIOsSWeO0qvNgaAxtoMrUcAbwBsAGQAVgBhAGwAdQBlAAAAAAAAAAHgyCm7rxpH
uEOLYoiJYrMHAAAAiqIOsSWeO0qvNgaAxtoMrVQAeQBwAGUAAAAAAAAA3F2NTaB5
QUyUSWjD/wWMDAcAAACKog6xJZ47Sq82BoDG2gytTAB2AGwAUgBlAHEAdQBpAHIA
ZQBtAGUAbgB0AAAAAAAAAMQsJcKMcndOqgE9C/4uuAkHAAAAiqIOsSWeO0qvNgaA
xtoMrUQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAAABeweUAS+ZrRpTlb5w2pkzg
BwAAAIqiDrElnjtKrzYGgMbaDK1EAGEAbQBhAGcAZQAAAAAAAAAsICBwVnvWSIR7
Eg/L5YtWBwAAAIqiDrElnjtKrzYGgMbaDK1BAHQAdABhAGMAawBTAHAAZQBlAGQA
AAAAAAAAE98O4zFWzEijqV40JSA7AAcAAACKog6xJZ47Sq82BoDG2gytVAB3AG8A
SABhAG4AZABlAGQAAAAAAAAAirQ673cQLEC4Y7EcrwLcfQcAAACKog6xJZ47Sq82
BoDG2gytUwB1AGIAVAB5AHAAZQAAAAAAAACD84ec8vDzTYJuYNEtw44oBwAAAIqi
DrElnjtKrzYGgMbaDK1SAGUAYQBjAGgAAAAAAAAA3VoW5c1Kt0uYl4cV0+nS5QcA
AACKog6xJZ47Sq82BoDG2gytSABlAGEAdgB5AAAAAAAAAEkl7x/U5S1Dtwatre9O
GnsHAAAAiqIOsSWeO0qvNgaAxtoMrUQAZQBmAGUAbgBzAGUAAAAAAAAA7h1vuES4
iEWrX6hKKTy2GAcAAACKog6xJZ47Sq82BoDG2gytSABQAFIAZQBzAHQAbwByAGUA
AAAAAAAA3z8QXDhCvEGg6Bjl8ZiqOgcAAACKog6xJZ47Sq82BoDG2gytTQBQAFIA
ZQBzAHQAbwByAGUAAAAAAAAAfmc4WZ94F0yynVlA0O0QWQcAAACKog6xJZ47Sq82
BoDG2gytUgBlAHYAaQB2AGUAcwAAAAAAAAA4k+FtvPcTRZP3Zprcj+8FBwAAAIqi
DrElnjtKrzYGgMbaDK1DAHUAcgBlAFMAdABhAHQAdQBzAEUAZgBmAGUAYwB0AAAA
AAAAAPbdATOoknJLgquvTx1OyIAHAAAAiqIOsSWeO0qvNgaAxtoMrUkARAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="9t0BM6iSckuCq69PHU7IgA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Name" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="z5qDdHflH06MxCOXdiUiig==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Description" minOccurs="1" od:jetType="memo" od:sqlSType="ntext" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="xCwlwoxyd06qAT0L/i64CQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="GoldValue" minOccurs="1" od:jetType="integer" od:sqlSType="smallint" od:nonNullable="yes" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="k6CrPgYu/U+ZKRf7WVEOhg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Type" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="AeDIKbuvGke4Q4tiiIlisw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LvlRequirement" minOccurs="1" od:jetType="integer" od:sqlSType="smallint" od:nonNullable="yes" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="3F2NTaB5QUyUSWjD/wWMDA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="SubType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="irQ673cQLEC4Y7EcrwLcfQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Damage" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="XsHlAEvma0aU5W+cNqZM4A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AttackSpeed" minOccurs="0" od:jetType="single" od:sqlSType="real" type="xsd:float">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="LCAgcFZ71kiEexIPy+WLVg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Format" type="10" value="Standard"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="TwoHanded" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="GUID" type="9" value="E98O4zFWzEijqV40JSA7AA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Reach" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="GUID" type="9" value="g/OHnPLw802CbmDRLcOOKA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Heavy" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="GUID" type="9" value="3VoW5c1Kt0uYl4cV0+nS5Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="12"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Defense" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="SSXvH9TlLUO3Bq2t704aew==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="13"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="HPRestore" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="7h1vuES4iEWrX6hKKTy2GA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="14"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MPRestore" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="3z8QXDhCvEGg6Bjl8ZiqOg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="15"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Revives" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="GUID" type="9" value="fmc4WZ94F0yynVlA0O0QWQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="16"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CureStatusEffect" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="GUID" type="9" value="OJPhbbz3E0WT92aa3I/vBQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="17"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PackOfDingoes/TopDown2dCharacterController/Assets/Assets/xml things DON'T DELETE/ItemDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="ItemDatabase.xsd" generated="2016-05-13T17:06:24">
<ItemDatabase>
<ID>1</ID>
<Name>Rusty Sword</Name>
<Description>An old rusty sword</Description>
<GoldValue>10</GoldValue>
<Type>WEAPON</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>SWORD</SubType>
<Damage>5</Damage>
<AttackSpeed>1</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>0</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>2</ID>
<Name>Rusty Mace</Name>
<Description>An old rust mace</Description>
<GoldValue>10</GoldValue>
<Type>WEAPON</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>MACE</SubType>
<Damage>10</Damage>
<AttackSpeed>0.5</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>1</Heavy>
<Defense>0</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>3</ID>
<Name>Rusty Spear</Name>
<Description>An old rusty spear</Description>
<GoldValue>10</GoldValue>
<Type>WEAPON</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>SPEAR</SubType>
<Damage>5</Damage>
<AttackSpeed>0.7</AttackSpeed>
<TwoHanded>1</TwoHanded>
<Reach>1</Reach>
<Heavy>0</Heavy>
<Defense>0</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>4</ID>
<Name>Thick Red Goop</Name>
<Description>A very crude HP potion</Description>
<GoldValue>25</GoldValue>
<Type>POTION</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>HP</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>0</Defense>
<HPRestore>25</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>5</ID>
<Name>Thick Blue Goop</Name>
<Description>A very crude MP potion</Description>
<GoldValue>25</GoldValue>
<Type>POTION</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>MP</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>0</Defense>
<HPRestore>0</HPRestore>
<MPRestore>10</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>6</ID>
<Name>Hide Helmet</Name>
<Description>A helmet made of hide</Description>
<GoldValue>5</GoldValue>
<Type>ARMOUR</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>HELMET</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>5</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>7</ID>
<Name>Hide Chest</Name>
<Description>A chest piece made of hide</Description>
<GoldValue>5</GoldValue>
<Type>ARMOUR</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>CHEST</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>15</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>8</ID>
<Name>Hide Gloves</Name>
<Description>A pair of gloves made of hide</Description>
<GoldValue>5</GoldValue>
<Type>ARMOUR</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>GLOVES</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>2</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>9</ID>
<Name>Hide Pants</Name>
<Description>A pair of pants made of hide</Description>
<GoldValue>5</GoldValue>
<Type>ARMOUR</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>PANTS</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>10</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>10</ID>
<Name>Hide Boots</Name>
<Description>A pait of boots made of hide</Description>
<GoldValue>5</GoldValue>
<Type>ARMOUR</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>BOOTS</SubType>
<Damage>0</Damage>
<AttackSpeed>0</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>3</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
<ItemDatabase>
<ID>11</ID>
<Name>Small Stick</Name>
<Description>An improvised wand</Description>
<GoldValue>10</GoldValue>
<Type>WEAPON</Type>
<LvlRequirement>0</LvlRequirement>
<SubType>WAND</SubType>
<Damage>1</Damage>
<AttackSpeed>2</AttackSpeed>
<TwoHanded>0</TwoHanded>
<Reach>0</Reach>
<Heavy>0</Heavy>
<Defense>0</Defense>
<HPRestore>0</HPRestore>
<MPRestore>0</MPRestore>
<Revives>0</Revives>
<CureStatusEffect>0</CureStatusEffect>
</ItemDatabase>
</dataroot>
